### ISSUE TITLE
plan of releasing code

### ISSUE THREAD

**Issue by ShoufaChen** [ArchipLab-LinfengZhang/Object-Detection-Knowledge-Distillation-ICLR2021#2]
Hi,

Thanks for the wonderful work.
May I ask when will you release the code?

**Comment by ShoufaChen** [comment]
Find the code in Supplementary material.
Thanks.

**Comment by Fly-dream12** [comment]
Where is the code and the paper, can you provide a link ？@ShoufaChen

**Comment by ShoufaChen** [comment]
https://openreview.net/attachment?id=uKhGRvM8QNH&name=supplementary_material

**Comment by Fly-dream12** [comment]
Is this method a kind of self knowledge distillation? Since the backbone is not changed ?
Can you leave your email address for further communication about this project ? @ShoufaChen
