### ISSUE TITLE
mmdetection version

### ISSUE THREAD

**Issue by yqjiang6** [ArchipLab-LinfengZhang/Object-Detection-Knowledge-Distillation-ICLR2021#9]
Hi! Could you please provide the specific version of the mmdetection used in your paper? I cloned the v2.18 from mmdetection repository and it seems like your code is incompatible with this version of mmdetection.
Thank You!

**Comment by Senwang98** [comment]
Hi, @yqjiang6 
Have you solved this version problem?

**Comment by ruiningTang** [comment]
I found the code is compatible with mmdet-2.3, and it works well for me.

**Comment by Senwang98** [comment]
@ruiningTang 
Ok, thanks bro!

**Comment by yqjiang6** [comment]
Thank for your reply. MMdet-2.3 works well!
